### PR TITLE
test: Check our config works on some example files

### LINKED ISSUE #7: Add unit tests.
At the very least, we should unit test the following:

1) `package.json`'s `peerDependencies` are also present (with same version) as `devDepenencies` (this is important for local development).
2) All configuration files can be opened without errors.

Unit tests should be run in Circle CI before packaging.

### PR DESCRIPTION
**Pull request by seb-cr**
There have been some errors caused by incompatible dependencies in our ESLint config that made it unusable. These should have been picked up by CI!

This PR is a first attempt at adding some tests. It's just a bash script that runs ESLint against some sample configs and files and reports back any errors. This should catch the major of problems and also lets us document by example _why_ we have certain rules turned off, for example `no-unused-expressions` when using `mixins/mocha` because `chai` assertions use a lot of these.

Closes #7

### CODE REVIEW

**Review by pauldolden — COMMENTED** [review]
This is a good idea, I guess each time we add a **_custom_** mixin, we add a test to cover as we would any other feature.

My bash is sketchy at best, but all seems work great so all good from my end on that front.

Only thing, the apiDoc test seems to be 'failing' for me, on `String` instead of `string` and also the line-breaks between tags (which I think should be there).

Are you getting these same warnings?

**Comment by seb-cr** [comment]
> Only thing, the apiDoc test seems to be 'failing' for me, on `String`/`Number` instead of `string`/`number` and also the line-breaks between tags (which I think should be there).

I saw those. They are only warnings, so not technically failing but still annoying. Did you get the same warnings when you were adding apiDoc to some other repos? Like you say blank lines between tags are pretty necessary for apiDoc (you need some visual grouping when there are so many tags) so we might want to consider turning this rule off in the apiDoc mixin.

**Comment by pauldolden** [comment]
> Did you get the same warnings when you were adding apiDoc to some other repos? Like you say blank lines between tags are pretty necessary for apiDoc (you need some visual grouping when there are so many tags) so we might want to consider turning this rule off in the apiDoc mixin.

I didn't get those no, but other rules were working. Could it be new rules added to the `eslint-plugin-jsdoc` in the updated version? Or could be that another plugin was broken because of the general version issues and wasn't applying this rule potentially?

Either way you're right, I think it should be turned off. As for the other ones, I think I was using `string` etc. so I don't think I got those either.

**Comment by seb-cr** [comment]
> Happy to appove though, if those changes constitute a different block of work/PR.

Yeah, this one is just tests, let's do another one for rule changes. Thanks!

**Review by pauldolden — APPROVED** [review]

**Pull request merged**
